# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoiceAssistant(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(-260, -120, 1351, 761))
        self.bg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.bg.setText("")
        self.bg.setScaledContents(False)
        self.bg.setObjectName("bg")

        self.jarvisGif1 = QtWidgets.QLabel(self.centralwidget)
        self.jarvisGif1.setGeometry(QtCore.QRect(270, 10, 311, 311))
        self.jarvisGif1.setText("")
        self.jarvisGif1.setPixmap(QtGui.QPixmap("../files/photos/ironman2.gif"))
        self.jarvisGif1.setScaledContents(True)
        self.jarvisGif1.setObjectName("jarvisGif1")

        self.jarvisGif2 = QtWidgets.QLabel(self.centralwidget)
        self.jarvisGif2.setGeometry(QtCore.QRect(20, 350, 301, 221))
        self.jarvisGif2.setText("")
        self.jarvisGif2.setPixmap(QtGui.QPixmap("../files/photos/ironman4.gif"))
        self.jarvisGif2.setScaledContents(True)
        self.jarvisGif2.setObjectName("jarvisGif2")

        self.jarvisGif3 = QtWidgets.QLabel(self.centralwidget)
        self.jarvisGif3.setGeometry(QtCore.QRect(550, 310, 281, 271))
        self.jarvisGif3.setText("")
        self.jarvisGif3.setPixmap(QtGui.QPixmap("../files/photos/ironman5.gif"))
        self.jarvisGif3.setScaledContents(True)
        self.jarvisGif3.setObjectName("jarvisGif3")

        self.pic1 = QtWidgets.QLabel(self.centralwidget)
        self.pic1.setGeometry(QtCore.QRect(340, 350, 81, 141))
        self.pic1.setText("")
        self.pic1.setPixmap(QtGui.QPixmap("../../../../Pictures/Wallpaper/03453768-85d6-465a-96c9-79d1445febc9.jpg"))
        self.pic1.setScaledContents(True)
        self.pic1.setObjectName("pic1")

        self.pic2 = QtWidgets.QLabel(self.centralwidget)
        self.pic2.setGeometry(QtCore.QRect(440, 350, 81, 141))
        self.pic2.setText("")
        self.pic2.setPixmap(QtGui.QPixmap("../../../../Pictures/Wallpaper/03453768-85d6-465a-96c9-79d1445febc9 - Copy.jpg"))
        self.pic2.setScaledContents(True)
        self.pic2.setObjectName("pic2")

        self.pushButtonStart = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStart.setGeometry(QtCore.QRect(340, 480, 81, 41))
        self.pushButtonStart.setStyleSheet("background-color:transparent;\n"
"font: 25pt \"Maiandra GD\";\n"
"color: rgb(85, 255, 255);")
        self.pushButtonStart.setObjectName("pushButtonStart")

        self.pushButtonExit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(440, 480, 81, 41))
        self.pushButtonExit.setStyleSheet("background-color:transparent;\n"
"font: 25pt \"Maiandra GD\";\n"
"color: rgb(85, 255, 255);")
        self.pushButtonExit.setObjectName("pushButtonExit")

        self.time = QtWidgets.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(50, 40, 221, 91))
        self.time.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"News706 BT\";\n"
"color:rgb(255,255,255);")
        self.time.setObjectName("Time")

        self.date = QtWidgets.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(590, 40, 221, 91))
        self.date.setStyleSheet("background-color: transparent;\n"
"font: 75 18pt \"News706 BT\";\n"
"color:rgb(255,255,255);")
        self.date.setObjectName("Date")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Voice Assitant App"))
        self.pushButtonStart.setText(_translate("MainWindow", "Start"))
        self.pushButtonExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_VoiceAssistant()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
